/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITeleporter,
  ITeleporterInterface,
} from "../../contracts/ITeleporter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "destinationChainId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
    ],
    name: "sendMessage",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITeleporter__factory {
  static readonly abi = _abi;
  static createInterface(): ITeleporterInterface {
    return new utils.Interface(_abi) as ITeleporterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITeleporter {
    return new Contract(address, _abi, signerOrProvider) as ITeleporter;
  }
}
