/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IReputationOracle,
  IReputationOracleInterface,
} from "../../../contracts/VerificationAttestor.sol/IReputationOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "verifier",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "increaseReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReputationOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationOracleInterface {
    return new utils.Interface(_abi) as IReputationOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReputationOracle {
    return new Contract(address, _abi, signerOrProvider) as IReputationOracle;
  }
}
