name: Infra smoke

on:
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        working-directory: infra
        run: |
          npm ci

      - name: Run infra smoke tests
        working-directory: infra
        env:
          # The workflow expects the repository to provide endpoints.json and teleporter.json
          # For PRs that change infra, authors should ensure tests are runnable or the job
          # will fail. For local-only tests, consider allowing a skip via inputs.
          # (No secrets are required for read-only tests.)
        run: |
          npx ts-node tests/smoke.ts
