/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IReputationOracle } from "./IReputationOracle";
export type { ReputationOracle } from "./ReputationOracle";
export type { VerificationAttestor } from "./VerificationAttestor";
